---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
# - id: trailing-whitespace
# - id: end-of-file-fixer
# - id: check-yaml
# - id: check-json
# - id: check-docstring-first
# -   id: flake8
#     args: [--max-line-length=100]
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
    args: [-l, '110']
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.1.0 # or specific tag
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --width, '150', --preserve-quotes]
files: (^src/.*py)|(.*yaml)
